name: Pipeline Production
run-name: Build ${{ inputs.web }}
on:
  workflow_dispatch:
    inputs:
      web:
        type: choice
        description: Web
        options: 
          - admin
          - seller
          - buyer

concurrency:
  group: environment-${{ inputs.web }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Preview
    runs-on: ubuntu-latest
    steps:
      - name: Build Preview
        run: |
          echo ${{ github.inputs.web }}
          sleep 30
          echo 'Build Preview'

  publish:
    name: Publish to Production
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: build
    steps:
      - name: Publish
        run: echo 'Publish'